# [START django_app]
runtime: python37
instance_class: F1
# instance_class: F4_1G

# 다음줄이 있으면 main.py가 필요없어지는 같다
# entrypoint: gunicorn -b :$PORT --threads=4 home.wsgi
# entrypoint: gunicorn -b :$PORT --threads=4 main:app

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

  # http를 https로 포워딩하기
  # https://stackoverflow.com/questions/33878825/how-to-permanently-redirect-http-and-www-urls-to-https

# [END django_app]
