# [START django_app]
runtime: python37

# 다음줄이 있으면 main.py가 필요없어지는 같다
# entrypoint: gunicorn -b :$PORT main.wsgi

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
# [END django_app]
