# Generated by Django 3.1.6 on 2021-06-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('n_collected', models.IntegerField(default=0)),
                ('n_voted', models.IntegerField(default=0)),
                ('amount_by_action', models.IntegerField(default=0)),
                ('amount_by_bonus', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('boo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.boo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.UniqueConstraint(fields=('boo', 'date'), name='daily unique reward'),
        ),
    ]
