# Generated by Django 3.0.7 on 2021-02-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
