# Generated by Django 3.0.7 on 2021-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
