# Generated by Django 3.0.7 on 2020-08-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eyemask',
            old_name='on',
            new_name='masked',
        ),
        migrations.RenameField(
            model_name='mouthmask',
            old_name='on',
            new_name='masked',
        ),
    ]
