# Generated by Django 3.0.7 on 2020-06-30 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getch.Boo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getch.Boo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PixProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Profile')),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.profile',),
        ),
        migrations.CreateModel(
            name='TextProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Profile')),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.profile',),
        ),
        migrations.CreateModel(
            name='VoteAB',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Post')),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.post',),
        ),
        migrations.CreateModel(
            name='VoteOX',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Post')),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.post',),
        ),
    ]
