# Generated by Django 3.0.7 on 2020-08-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvoteab',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='postvoteox',
            name='post_ptr',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostVoteAB',
        ),
        migrations.DeleteModel(
            name='PostVoteOX',
        ),
    ]
