# Generated by Django 3.0.7 on 2020-08-10 08:59

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._profilepix_path),
        ),
    ]
