# Generated by Django 3.0.7 on 2020-06-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0002_boo_pixprofile_post_profile_textprofile_voteab_voteox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePix',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Profile')),
                ('src', models.ImageField(blank=True, max_length=500, null=True, upload_to='test/')),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.profile',),
        ),
        migrations.RenameModel(
            old_name='VoteAB',
            new_name='PostVoteAB',
        ),
        migrations.RenameModel(
            old_name='VoteOX',
            new_name='PostVoteOX',
        ),
        migrations.RenameModel(
            old_name='PixProfile',
            new_name='ProfileText',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='TextProfile',
        ),
    ]
