# Generated by Django 3.0.7 on 2020-08-10 09:01

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0002_profile_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pix',
            field=models.ImageField(default='material/profile.png', max_length=500, upload_to=getch.models._profilepix_path),
        ),
    ]
