# Generated by Django 3.1.6 on 2021-06-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0002_auto_20210611_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='amount',
            new_name='amount_by_collect',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='amount_by_action',
            new_name='amount_by_vote',
        ),
    ]
