# Generated by Django 3.0.7 on 2021-01-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0002_boo_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boo',
            name='archived',
        ),
        migrations.AddField(
            model_name='boo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
