# Generated by Django 3.1.6 on 2021-03-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0002_auto_20210309_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
