# Generated by Django 3.0.7 on 2020-08-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0002_auto_20200811_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flager_users', to='getch.Boo', verbose_name='Boo'),
        ),
    ]
