# Generated by Django 3.0.7 on 2021-01-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0003_auto_20210119_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boo',
            name='fashiontems',
        ),
        migrations.RemoveField(
            model_name='boo',
            name='styletags',
        ),
        migrations.DeleteModel(
            name='Fashiontem',
        ),
        migrations.DeleteModel(
            name='Styletag',
        ),
    ]
