# Generated by Django 3.0.7 on 2020-06-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0003_auto_20200630_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletext',
            name='profile_ptr',
        ),
        migrations.AddField(
            model_name='profile',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='test/'),
        ),
        migrations.DeleteModel(
            name='ProfilePix',
        ),
        migrations.DeleteModel(
            name='ProfileText',
        ),
    ]
