# Generated by Django 3.0.7 on 2020-08-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0003_post2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='Post',
        ),
    ]
