# Generated by Django 3.1.6 on 2021-06-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0003_auto_20210611_1043'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reward',
            name='daily unique reward',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='date',
        ),
    ]
