# Generated by Django 3.1.6 on 2021-03-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0003_pix_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pix',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
