# Generated by Django 3.0.7 on 2021-02-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0003_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='public',
        ),
    ]
