# Generated by Django 3.0.7 on 2020-08-12 06:55

from django.db import migrations, models
import django.db.models.deletion
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0003_auto_20200812_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getch.Boo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostVoteAB',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Post')),
                ('pix_a', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._postpix_path)),
                ('pix_b', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._postpix_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.post',),
        ),
        migrations.CreateModel(
            name='PostVoteOX',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Post')),
                ('pix', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._postpix_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.post',),
        ),
    ]
