# Generated by Django 3.1.6 on 2021-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0004_auto_20210309_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pix',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pix',
            name='tokens',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
