# Generated by Django 3.0.7 on 2020-08-19 08:49

from django.db import migrations, models
import django.db.models.deletion
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0004_auto_20200819_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVoteAB',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Post')),
                ('pix_a', models.ImageField(max_length=500, upload_to=getch.models._postpix_path)),
                ('pix_b', models.ImageField(max_length=500, upload_to=getch.models._postpix_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.post',),
        ),
        migrations.CreateModel(
            name='PostVoteOX',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Post')),
                ('pix', models.ImageField(max_length=500, upload_to=getch.models._postpix_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.post',),
        ),
    ]
