# Generated by Django 3.0.7 on 2020-06-30 09:49

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0004_auto_20200630_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='profile_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._profilepix_path),
        ),
    ]
