# Generated by Django 3.0.7 on 2020-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0004_post_postvoteab_postvoteox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('PIX', 'pix'), ('TEXT', 'text')], default='IMAGE', max_length=5),
        ),
    ]
