# Generated by Django 3.0.7 on 2021-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0004_remove_link_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(max_length=300),
        ),
    ]
