# Generated by Django 3.0.7 on 2021-01-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0004_auto_20210119_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_comment_set', to='getch.Boo'),
        ),
    ]
