# Generated by Django 3.1.6 on 2021-06-11 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0004_auto_20210611_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
