# Generated by Django 3.0.7 on 2020-08-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0005_auto_20200812_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('PIX', 'pix'), ('TEXT', 'text')], default='PIX', max_length=5),
        ),
    ]
