# Generated by Django 3.0.7 on 2021-01-19 14:57

from django.db import migrations, models
import django.db.models.deletion
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0005_comment_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentpix',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(max_length=500, upload_to=getch.models._commentpix_path)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
