# Generated by Django 3.0.7 on 2021-02-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0005_auto_20210207_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(max_length=200),
        ),
    ]
