# Generated by Django 3.1.6 on 2021-03-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0005_auto_20210312_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pix',
            name='tokens',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
