# Generated by Django 3.1.6 on 2021-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0005_reward_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='amount_by_bonus',
            new_name='bonus_reward',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='amount_by_collect',
            new_name='collect_reward',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='amount_by_vote',
            new_name='vote_reward',
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.UniqueConstraint(fields=('boo', 'date'), name='daily unique reward'),
        ),
    ]
