# Generated by Django 3.0.7 on 2020-08-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0005_postvoteab_postvoteox'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvoteab',
            name='pixlabel_a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postvoteab',
            name='pixlabel_b',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
