# Generated by Django 3.1.6 on 2021-03-17 19:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0006_auto_20210316_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='옷장이름', max_length=200)),
                ('pixs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.boo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
