# Generated by Django 3.0.7 on 2021-02-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0006_auto_20210207_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='links',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
