# Generated by Django 3.0.7 on 2020-08-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0006_auto_20200827_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvoteox',
            name='keys',
            field=models.CharField(choices=[('OX', 'OX'), ('SM', '살말')], default='OX', max_length=2),
        ),
    ]
