# Generated by Django 3.0.7 on 2020-08-12 15:13

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0006_auto_20200812_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='base', max_length=50)),
                ('pix', models.ImageField(max_length=500, upload_to=getch.models._characterpix_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
