# Generated by Django 3.0.7 on 2021-01-21 05:54

from django.db import migrations, models
import django.db.models.deletion
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0006_commentpix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQA',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Post')),
                ('pix', models.ImageField(max_length=500, upload_to=getch.models._postpix_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.post',),
        ),
    ]
