# Generated by Django 3.0.7 on 2020-07-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0006_user_boo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boo',
            old_name='profile_id',
            new_name='profile_selected',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='boo_id',
            new_name='boo_selected',
        ),
    ]
