# Generated by Django 3.0.7 on 2020-08-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0007_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.Character'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('CHARACTER', 'character'), ('PIX', 'pix'), ('TEXT', 'text')], default='CHARACTER', max_length=10),
        ),
    ]
