# Generated by Django 3.1.6 on 2021-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0007_boo_coltagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='checkin_reward',
            field=models.IntegerField(default=0),
        ),
    ]
