# Generated by Django 3.1.6 on 2021-03-17 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0007_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='pixs',
        ),
        migrations.AddField(
            model_name='collection',
            name='pixids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
