# Generated by Django 3.0.7 on 2020-07-09 08:50

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0007_auto_20200702_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvoteab',
            name='pix_a',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._postpix_path),
        ),
        migrations.AddField(
            model_name='postvoteab',
            name='pix_b',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._postpix_path),
        ),
        migrations.AddField(
            model_name='postvoteox',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._postpix_path),
        ),
    ]
