# Generated by Django 3.0.7 on 2020-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0007_postvoteox_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
