# Generated by Django 3.0.7 on 2021-01-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0007_postqa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boo',
            name='nfollowers',
        ),
        migrations.RemoveField(
            model_name='boo',
            name='nposts',
        ),
    ]
