# Generated by Django 3.1.6 on 2021-03-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0008_auto_20210317_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='pixids',
        ),
    ]
