# Generated by Django 3.0.7 on 2021-02-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0008_auto_20210207_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boo',
            name='links',
        ),
    ]
