# Generated by Django 3.1.6 on 2021-06-25 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0008_reward_checkin_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contentwork',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agenda', models.TextField(blank=True, default='', max_length=200)),
                ('profiles', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.boo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
