# Generated by Django 3.0.7 on 2020-08-13 01:00

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0008_auto_20200813_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._profilepix_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('CHARACTER', 'character'), ('IMAGE', 'image'), ('TEXT', 'text')], default='CHARACTER', max_length=10),
        ),
    ]
