# Generated by Django 3.0.7 on 2020-09-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0009_boo_nposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='nfollowers',
            field=models.IntegerField(default=0),
        ),
    ]
