# Generated by Django 3.0.7 on 2020-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0009_auto_20200709_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvoteab',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='postvoteab',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='postvoteab',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='postvoteox',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='postvoteox',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='postvoteox',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='post',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
