# Generated by Django 3.1.6 on 2021-03-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0009_remove_collection_pixids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('pix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getch.pix')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
