# Generated by Django 3.0.7 on 2021-02-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0009_remove_boo_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='links',
            field=models.ManyToManyField(blank=True, to='getch.Link'),
        ),
    ]
