# Generated by Django 3.1.6 on 2021-06-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0009_contentwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentwork',
            name='agenda',
            field=models.CharField(max_length=30),
        ),
    ]
