# Generated by Django 3.0.7 on 2021-02-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0010_boo_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestboo',
            fields=[
                ('boo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getch.Boo')),
            ],
            options={
                'abstract': False,
            },
            bases=('getch.boo',),
        ),
    ]
