# Generated by Django 3.0.7 on 2020-09-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0010_boo_nfollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nvotes_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='nvotes_up',
            field=models.IntegerField(default=0),
        ),
    ]
