# Generated by Django 3.0.7 on 2020-08-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0011_flager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_score',
        ),
    ]
