# Generated by Django 3.1.6 on 2021-06-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0011_postage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
