# Generated by Django 3.1.6 on 2021-06-25 21:05

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0012_postage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postage',
            name='pix_b',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._postagepix_path),
        ),
    ]
