# Generated by Django 3.1.6 on 2021-03-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0012_pick_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pix',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Pick',
        ),
    ]
