# Generated by Django 3.0.7 on 2020-08-05 00:42

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0012_auto_20200804_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pix_base',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._profilepix_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='txt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('PIX', 'profilepix'), ('TXT', 'profiletxt')], default='PIX', max_length=5),
        ),
    ]
