# Generated by Django 3.0.7 on 2020-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyemask',
            name='height',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='mouthmask',
            name='height',
            field=models.FloatField(default=30),
        ),
    ]
