# Generated by Django 3.0.7 on 2020-08-05 02:14

from django.db import migrations, models
import django.db.models.deletion
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0013_auto_20200805_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pix', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._maskpix_path)),
                ('top', models.FloatField(default=0)),
                ('left', models.FloatField(default=0)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='eye_mask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_mask', to='getch.Mask'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mouth_mask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouth_mask', to='getch.Mask'),
        ),
    ]
