# Generated by Django 3.0.7 on 2020-11-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0013_auto_20200909_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styletag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='boo',
            name='styletags',
            field=models.ManyToManyField(blank=True, to='getch.Styletag'),
        ),
    ]
