# Generated by Django 3.1.6 on 2021-07-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0014_boo_contentwork_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='nomore_today',
            field=models.BooleanField(default=False),
        ),
    ]
