# Generated by Django 3.0.7 on 2020-08-05 04:18

from django.db import migrations, models
import django.db.models.deletion
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0014_auto_20200805_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskBase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EYE', 'eye_mask'), ('MOUTH', 'mouth_mask')], default='EYE', max_length=5)),
                ('pix', models.ImageField(max_length=500, upload_to=getch.models._maskpix_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mask',
            name='pix',
        ),
        migrations.AlterField(
            model_name='profile',
            name='eye_mask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye', to='getch.Mask'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mouth_mask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouth', to='getch.Mask'),
        ),
        migrations.AddField(
            model_name='mask',
            name='mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.MaskBase'),
        ),
    ]
