# Generated by Django 3.1.6 on 2021-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0014_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='activity',
            field=models.JSONField(null=True),
        ),
    ]
