# Generated by Django 3.1.6 on 2021-07-26 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0015_reward_nomore_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, max_length=200, null=True)),
                ('coverpix', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._coverpix_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.boo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
