# Generated by Django 3.1.6 on 2021-02-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0015_session_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='activity',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
