# Generated by Django 3.1.6 on 2021-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0016_collection_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='desc',
            field=models.TextField(default='', max_length=200),
        ),
    ]
