# Generated by Django 3.1.6 on 2021-07-26 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0016_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('AB', 'AB타입'), ('OX', 'OX타입'), ('QA', '주관식'), ('MC', '다중선택형')], default='AB', max_length=2)),
                ('question', models.TextField(blank=True, max_length=300, null=True)),
                ('pix_0', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path)),
                ('pix_1', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path)),
                ('label_0', models.TextField(blank=True, max_length=100, null=True)),
                ('label_1', models.TextField(blank=True, max_length=100, null=True)),
                ('multi_choices', models.TextField(blank=True, max_length=200, null=True)),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.research')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
