# Generated by Django 3.1.6 on 2021-02-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('getch', '0016_auto_20210216_1137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flager',
            unique_together={('content_type', 'object_id', 'user', 'status', 'note')},
        ),
    ]
