# Generated by Django 3.1.6 on 2021-07-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0017_researchitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchitem',
            old_name='label_0',
            new_name='pixlabel_0',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='label_1',
            new_name='pixlabel_1',
        ),
    ]
