# Generated by Django 3.1.6 on 2021-02-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0017_auto_20210216_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='activity',
        ),
        migrations.AddField(
            model_name='session',
            name='view',
            field=models.JSONField(default=list, null=True),
        ),
    ]
