# Generated by Django 3.1.6 on 2021-03-23 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0017_collection_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
