# Generated by Django 3.0.7 on 2020-08-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0017_auto_20200805_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eye_mask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye', to='getch.Mask'),
        ),
    ]
