# Generated by Django 3.1.6 on 2021-03-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0018_pick_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
