# Generated by Django 3.1.6 on 2021-02-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0018_auto_20210217_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='SessionManager',
        ),
    ]
