# Generated by Django 3.1.6 on 2021-07-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0018_auto_20210726_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
