# Generated by Django 3.0.7 on 2020-08-05 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0018_profile_eye_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mouth_mask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouth', to='getch.Mask'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getch.MaskBase'),
        ),
    ]
