# Generated by Django 3.1.6 on 2021-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0019_research_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='due',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
