# Generated by Django 3.1.6 on 2021-02-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0019_auto_20210217_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionManager',
            new_name='Session',
        ),
    ]
