# Generated by Django 3.1.6 on 2021-03-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0019_auto_20210323_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pix',
            name='outlink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
