# Generated by Django 3.1.6 on 2021-07-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0020_auto_20210729_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='gender',
            field=models.CharField(choices=[('X', 'X'), ('M', 'M'), ('F', 'F')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='preq',
            field=models.BooleanField(default=False),
        ),
    ]
