# Generated by Django 3.1.6 on 2021-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0020_auto_20210324_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
