# Generated by Django 3.1.6 on 2021-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0021_auto_20210729_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchitem',
            name='pixlabel_0',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='pixlabel_1',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='question',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
