# Generated by Django 3.1.6 on 2021-07-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0022_auto_20210729_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='pixlabel_0',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='pixlabel_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
