# Generated by Django 3.1.6 on 2021-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0023_auto_20210729_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='researched',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
