# Generated by Django 3.1.6 on 2021-08-02 01:59

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0025_auto_20210801_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchitem',
            name='multi_choices',
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_0',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mc_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_0',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_10',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_11',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_5',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_6',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_7',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_8',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='mcpix_9',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path),
        ),
    ]
