# Generated by Django 3.1.6 on 2021-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0026_auto_20210802_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
