# Generated by Django 3.1.6 on 2021-08-02 15:22

from django.db import migrations, models
import django.utils.timezone
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0027_auto_20210802_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='coverpix_0',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._brandpix_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='coverpix_1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._brandpix_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='coverpix_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._brandpix_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='coverpix_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._brandpix_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='coverpix_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._brandpix_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='brand',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='established',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._brandpix_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_kr',
            field=models.CharField(default='', max_length=50),
        ),
    ]
