# Generated by Django 3.1.6 on 2021-08-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0028_auto_20210802_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
