# Generated by Django 3.1.6 on 2021-08-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0029_brand_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_0',
            new_name='mclabel_0',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_1',
            new_name='mclabel_1',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_10',
            new_name='mclabel_10',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_11',
            new_name='mclabel_11',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_2',
            new_name='mclabel_2',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_3',
            new_name='mclabel_3',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_4',
            new_name='mclabel_4',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_5',
            new_name='mclabel_5',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_6',
            new_name='mclabel_6',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_7',
            new_name='mclabel_7',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_8',
            new_name='mclabel_8',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='mc_9',
            new_name='mclabel_9',
        ),
    ]
