# Generated by Django 3.1.6 on 2021-08-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0031_auto_20210802_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='nationality',
            new_name='origin',
        ),
    ]
