# Generated by Django 3.1.6 on 2021-08-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0032_auto_20210803_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
