# Generated by Django 3.1.6 on 2021-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0034_boo_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix',
            name='type',
            field=models.CharField(choices=[('X', 'X'), ('M', '남자착장'), ('F', '여자착장'), ('T', '아이템')], default='X', max_length=1),
        ),
    ]
