# Generated by Django 3.1.6 on 2021-08-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0036_auto_20210805_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pix',
            name='type',
        ),
    ]
