# Generated by Django 3.1.6 on 2021-08-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0037_remove_pix_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix',
            name='type',
            field=models.CharField(choices=[('X', '없음'), ('M', '남자착장'), ('F', '여자착장'), ('T', '아이템')], default='F', max_length=1),
        ),
    ]
