# Generated by Django 3.1.6 on 2021-08-06 08:46

from django.db import migrations, models
import django.utils.timezone
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0038_pix_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoptem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('shopix_0', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._itempix_path)),
                ('shopix_1', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._itempix_path)),
                ('shopix_2', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._itempix_path)),
                ('shopix_3', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._itempix_path)),
                ('shopix_4', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._itempix_path)),
                ('desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
