# Generated by Django 3.1.6 on 2021-08-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0040_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
