# Generated by Django 3.1.6 on 2021-08-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0042_auto_20210806_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoptem',
            new_name='Item',
        ),
    ]
