# Generated by Django 3.1.6 on 2021-08-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0043_auto_20210807_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shopix_0',
            new_name='pix_0',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shopix_1',
            new_name='pix_1',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shopix_2',
            new_name='pix_2',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shopix_3',
            new_name='pix_3',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shopix_4',
            new_name='pix_4',
        ),
    ]
