# Generated by Django 3.1.6 on 2021-08-07 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0045_item_out_of_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoptem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, max_length=200, null=True)),
                ('listing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
