# Generated by Django 3.1.6 on 2021-08-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0046_shoptem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoptem',
            name='desc',
        ),
    ]
