# Generated by Django 3.1.6 on 2021-08-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0048_auto_20210807_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getch.item'),
        ),
    ]
