# Generated by Django 3.1.6 on 2021-08-07 15:27

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0049_auto_20210807_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pix_0',
            field=models.ImageField(default='', max_length=500, upload_to=getch.models._itempix_path),
        ),
    ]
