# Generated by Django 3.1.6 on 2021-08-07 20:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0053_auto_20210807_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pix_wide',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._itempix_path),
        ),
        migrations.CreateModel(
            name='raffle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deduction', models.IntegerField(default=0)),
                ('listing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getch.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
