# Generated by Django 3.1.6 on 2021-08-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0054_auto_20210807_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
