# Generated by Django 3.1.6 on 2021-08-08 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0055_raffle_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('IN-00', '출첵밸런스게임'), ('IN-01', '매일밸런스게임'), ('IN-02', '옷장넣기'), ('IN-03', '리서치참여'), ('IN-04', '인터뷰참여'), ('OUT-00', '후원'), ('OUT-01', '래플'), ('OUT-02', '쇼핑')], default='IN-00', max_length=6)),
                ('amount', models.IntegerField(default=0)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
