# Generated by Django 3.1.6 on 2021-08-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0056_auto_20210808_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, '출첵밸런스게임'), (1, '매일밸런스게임'), (2, '옷장넣기'), (3, '리서치참여'), (4, '인터뷰참여'), (5, '첫방문환영'), (100, '후원'), (101, '래플'), (102, '쇼핑')], default=0),
        ),
    ]
