# Generated by Django 3.1.6 on 2021-08-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0057_auto_20210808_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
