# Generated by Django 3.1.6 on 2021-08-08 23:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0058_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[(0, '출첵밸런스게임'), (1, '매일밸런스게임'), (2, '옷장넣기'), (3, '리서치참여'), (4, '인터뷰참여'), (5, '첫방문환영'), (100, '후원'), (101, '래플'), (102, '쇼핑')], default=0)),
                ('amount', models.IntegerField(default=0)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
