# Generated by Django 3.1.6 on 2021-08-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0059_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.wallet'),
        ),
    ]
