# Generated by Django 3.1.6 on 2021-08-09 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0061_raffle_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.boo'),
        ),
    ]
