# Generated by Django 3.1.6 on 2021-08-09 08:36

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0062_transaction_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='agelabel',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._labelpix_path),
        ),
        migrations.AddField(
            model_name='bodylabel',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._labelpix_path),
        ),
        migrations.AddField(
            model_name='genderlabel',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._labelpix_path),
        ),
        migrations.AddField(
            model_name='itemlabel',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._labelpix_path),
        ),
        migrations.AddField(
            model_name='stylelabel',
            name='pix',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._labelpix_path),
        ),
    ]
