# Generated by Django 3.1.6 on 2021-08-11 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0063_auto_20210809_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffeecoupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('listing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getch.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
