# Generated by Django 3.1.6 on 2021-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0064_coffeecoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
