# Generated by Django 3.1.6 on 2021-08-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0065_research_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
