# Generated by Django 3.1.6 on 2021-08-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0066_researchitem_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchitem',
            name='pub_date',
        ),
    ]
