# Generated by Django 3.1.6 on 2021-08-13 16:31

from django.db import migrations, models
import django.utils.timezone
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0067_remove_researchitem_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashgame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('AB', 'AB타입')], default='AB', max_length=3)),
                ('text', models.TextField(blank=True, max_length=100, null=True)),
                ('published', models.BooleanField(default=False)),
                ('reward', models.IntegerField(default=10)),
                ('gender', models.CharField(choices=[('X', 'X'), ('M', 'M'), ('F', 'F')], default='X', max_length=1)),
                ('pix_0', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path)),
                ('pixlabel_0', models.CharField(blank=True, max_length=20, null=True)),
                ('pix_1', models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._researchitempix_path)),
                ('pixlabel_1', models.CharField(blank=True, max_length=20, null=True)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
