# Generated by Django 3.1.6 on 2021-08-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0068_flashgame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='who',
            new_name='client',
        ),
    ]
