# Generated by Django 3.1.6 on 2021-08-15 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0069_auto_20210815_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_receiver_set', to='getch.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, '출첵게임'), (1, '매일밸런스게임'), (2, '옷장넣기'), (3, '리서치참여'), (4, '인터뷰참여'), (5, '첫방문환영'), (6, '기본정보입력'), (7, '관심스타일입력'), (8, '관심아이템입력'), (100, '후원'), (101, '래플'), (102, '쇼핑')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_sender_set', to='getch.wallet'),
        ),
    ]
