# Generated by Django 3.1.6 on 2021-08-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0071_auto_20210815_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
    ]
