# Generated by Django 3.1.6 on 2021-08-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0074_auto_20210816_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='help',
            field=models.BooleanField(default=True),
        ),
    ]
