# Generated by Django 3.1.6 on 2021-08-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0077_mobileverifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boo',
            name='help',
        ),
        migrations.AddField(
            model_name='user',
            name='help',
            field=models.BooleanField(default=True),
        ),
    ]
