# Generated by Django 3.1.6 on 2021-08-24 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0079_user_grcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashgametag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.flashgame')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.boo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
