# Generated by Django 3.1.6 on 2021-08-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0082_auto_20210824_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancegameRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pix_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_0_balancegamerecord_set', to='getch.pix')),
                ('pix_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_1_balancegamerecord_set', to='getch.pix')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.boo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
