# Generated by Django 3.1.6 on 2021-08-29 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0083_balancegamerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancegamerecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
