# Generated by Django 3.1.6 on 2021-08-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0084_balancegamerecord_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancegamerecord',
            old_name='result',
            new_name='chosen',
        ),
    ]
