# Generated by Django 3.1.6 on 2021-08-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0085_auto_20210829_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '남성'), (1, '여성')], default=1),
        ),
    ]
