# Generated by Django 3.1.6 on 2021-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0087_research_time_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix',
            name='tokens_ko',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
