# Generated by Django 3.1.6 on 2021-09-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0089_auto_20210928_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeecoupon',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.wallet'),
        ),
        migrations.AddField(
            model_name='shoptem',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.wallet'),
        ),
    ]
