# Generated by Django 3.1.6 on 2021-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0090_auto_20210928_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, '출첵게임'), (1, '매일밸런스게임'), (2, '옷장넣기'), (3, '리서치참여'), (4, '인터뷰참여'), (5, '첫방문환영'), (6, '기본정보입력'), (7, '관심스타일입력'), (8, '관심아이템입력'), (50, '테스트 INFLOW'), (100, '후원'), (101, '래플'), (102, '쇼핑'), (103, '커피쿠폰')], default=0),
        ),
    ]
