# Generated by Django 3.1.6 on 2021-09-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0091_auto_20210928_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='notihistory',
            name='ordercode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
