# Generated by Django 3.1.6 on 2021-10-05 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0092_notihistory_ordercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=20)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('detail', models.CharField(blank=True, max_length=20, null=True)),
                ('pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('texture', models.CharField(blank=True, max_length=20, null=True)),
                ('look', models.CharField(blank=True, max_length=20, null=True)),
                ('length', models.CharField(blank=True, max_length=20, null=True)),
                ('sleeve_length', models.CharField(blank=True, max_length=20, null=True)),
                ('neckline', models.CharField(blank=True, max_length=20, null=True)),
                ('fit', models.CharField(blank=True, max_length=20, null=True)),
                ('shape', models.CharField(blank=True, max_length=20, null=True)),
                ('heel_height', models.CharField(blank=True, max_length=20, null=True)),
                ('toe_type', models.CharField(blank=True, max_length=20, null=True)),
                ('heel_shape', models.CharField(blank=True, max_length=20, null=True)),
                ('sole_type', models.CharField(blank=True, max_length=20, null=True)),
                ('strap', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('main_material', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_material', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.pix')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
