# Generated by Django 3.1.6 on 2021-10-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0093_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix',
            name='taggerlog',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
