# Generated by Django 3.1.6 on 2021-10-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0094_pix_taggerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getch.boo'),
        ),
    ]
