# Generated by Django 3.1.6 on 2021-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0096_raffle_send_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='single_choice_only',
            field=models.BooleanField(default=False),
        ),
    ]
