# Generated by Django 3.1.6 on 2021-10-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0099_auto_20211017_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancegamerecord',
            name='tag_0',
        ),
        migrations.RemoveField(
            model_name='balancegamerecord',
            name='tag_1',
        ),
        migrations.AddField(
            model_name='balancegamerecord',
            name='tag_neg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_neg_balancegamerecord_set', to='getch.tag'),
        ),
        migrations.AddField(
            model_name='balancegamerecord',
            name='tag_pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_pos_balancegamerecord_set', to='getch.tag'),
        ),
    ]
