# Generated by Django 3.1.6 on 2021-10-21 14:45

from django.db import migrations, models
import getch.models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0100_auto_20211017_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pix_detail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=getch.models._itempix_path),
        ),
    ]
