# Generated by Django 3.1.6 on 2021-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0101_item_pix_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='winner_notice',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
