# Generated by Django 3.1.6 on 2021-10-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getch', '0102_raffle_winner_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='winner_notice',
        ),
    ]
