from django.urls import path
from django.conf.urls import include
from . import views as v

urlpatterns = [
    path('mvp1', v.play, name='play'),
    path('', v.discover, name='discover'),
    # path('profiler', v.profiler, name='profiler'),
    path('company/', v.company, name='company'),
    path('company/recruit/', v.company_recruit, name='company_recruit'),
    path('landing/', v.landing, name='landing'),
    path('test/', v.test, name='test'),
    # path('testbed/', v.testbed, name='testbed'),
    # path('memb/', v.memb, name='memb'),
    path('privacy/', v.privacy, name='privacy'),
    path('policy/', v.policy, name='policy'),
    path('recruit/', v.recruit, name='recruit'),
    path('accounts/', include('allauth.urls')),
    # path('login/', v.Login.as_view(), name='login'),
    path('logout/', v.Logout.as_view(), name='logout'),
    # path('authorpage/<int:boo_id>/', v.authorpage, name='authorpage'),
    # path('posts/', v.get_posts, name='get_posts'),
    # path('posts/ids/', v.get_iposts, name='get_iposts'),
    # path('posts/ids/', v.get_iposts, name='get_iposts'),
    # path('posts/iposts/', v.get_iposts, name='get_iposts'),
    path('posts/iposts/<str:type>/', v.get_iposts, name='get_iposts'),
    # path('posts/iposts/<int:boo_id>/', v.get_ibooposts, name='get_ibooposts'),
    path('post/<int:post_id>/', v.get_post, name='get_post'),
    path('post/<int:post_id>/boo/', v.get_boopost, name='get_boopost'),
    path('post/<int:post_id>/icomments/', v.get_icomments, name='get_icomments'),
    # path('post/<int:post_id>/comments/', v.get_comments, name='get_comments'),
    path('post/<int:post_id>/vote/', v.vote, name='vote'),
    path('post/<int:post_id>/voters/', v.voters, name='voters'),
    path('post/<int:post_id>/ivoters/<int:act>/', v.get_ivoters, name='get_ivoters'),
    path('post/save/', v.post_save, name='post_save'),
    path('post/<int:post_id>/delete/', v.post_delete, name='post_delete'),
    path('comment/<int:comment_id>/', v.get_comment, name='get_comment'),
    path('comment/<int:comment_id>/like/', v.like_comment, name='like_comment'),
    path('comment/<int:comment_id>/delike/', v.delike_comment, name='delike_comment'),
    path('comment/save/', v.comment_save, name='comment_save'),

    path('boos/iboos/<str:type>/', v.get_iboos, name='get_iboos'),
    path('boo/<int:boo_id>/follow/', v.follow, name='follow'),
    path('boo/<int:boo_id>/unfollow/', v.unfollow, name='unfollow'),
    path('boo/<int:boo_id>/set/', v.set_boo, name='set_boo'),
    path('boo/<int:boo_id>/network/', v.network, name='network'),
    # path('boo/<int:boo_id>/posts/', v.boo_posts, name='boo_posts'),
    # path('boo/<int:boo_id>/iposts/', v.get_ibooposts, name='get_ibooposts'),
    path('boo/<int:boo_id>/iposts/<str:type>/', v.get_ibooposts, name='get_ibooposts'),
    path('boo/<int:boo_id>/ifollowers/', v.get_ifollowers, name='get_ifollowers'),

    path('boo/<int:boo_id>/profile/pix/', v.boo_profilepix, name='boo_profilepix'),
    path('boo/<int:boo_id>/baseboo/', v.get_baseboo, name='get_baseboo'),
    # path('boo/<int:boo_id>/voter/', v.get_voter, name='get_voter'),
    # path('boo/<int:boo_id>/follower/', v.get_follower, name='get_follower'),
    # path('boo/<int:boo_id>/moreinfo/', v.boo_moreinfo, name='boo_moreinfo'),
    # path('boo/profile/save/', v.profile_save, name='profile_save'),
    path('boo/profile/delete/', v.profile_delete, name='profile_delete'),
    # path('boo/new/', v.boo_new, name='boo_new'),
    path('user/', v.get_user, name='get_user'),
    path('user/other_boos/', v.other_boos, name='other_boos'),

    # path('styletags/tag/<int:tag_id>', v.styletags_tag, name='styletags_tag'),
    # path('styletags/untag/<int:tag_id>', v.styletags_untag, name='styletags_untag'),
    #
    # path('fashiontems/tag/<int:item_id>', v.fashiontems_tag, name='fashiontems_tag'),
    # path('fashiontems/untag/<int:item_id>', v.fashiontems_untag, name='fashiontems_untag'),

    path('boo/save/', v.boo_save, name='boo_save'),
    # path('boo/create/', v.boo_create, name='boo_create'),

    path('search/<str:keywords>/', v.search, name='search'),
    path('search/pix/<int:pix_id>/', v.search_by_pix, name='search_by_pix'),
    path('search/keyword/<str:keyword>/', v.search_by_keyword, name='search_by_keyword'),
    path('search/collection/<int:collection_id>/', v.search_by_collection, name='search_by_collection'),

    path('link/add/', v.link_add, name='link_add'),
    path('link/edit/', v.link_edit, name='link_edit'),
    path('link/delete/<int:link_id>/', v.link_delete, name='link_delete'),

    path('mbti/<str:type>/iposts/', v.get_mbti_iposts, name='get_mbti_iposts'),
    # path('mbti/<str:type>/result/base/', v.mbtiresult_base, name='mbtiresult_base'),

    path('pix/ipixs/', v.get_ipixs, name='get_ipixs'),
    path('pix/<int:pix_id>/', v.get_pix, name='get_pix'),

    path('collection/icols/', v.get_icols, name='get_icols'),
    path('collection/create/<str:name>/', v.create_collection, name='create_collection'),
    path('collection/<int:collection_id>/', v.get_collection, name='get_collection'),
    path('collection/<int:collection_id>/base/', v.get_collection_base, name='get_collection_base'),
    path('collection/<int:collection_id>/ipixs/', v.get_collection_ipixs, name='get_collection_ipixs'),
    path('collection/<int:collection_id>/ipicks/', v.get_ipicks, name='get_ipicks'),
    path('collection/<int:collection_id>/collect/<int:pix_id>/', v.collect_pix, name='collect_pix'),
    path('collection/<int:collection_id>/delpicks/<str:pick_ids>/', v.remove_picks, name='remove_picks'),

    path('pick/<int:pick_id>/', v.get_pick, name='get_pick'),

    path('user2/', v.get_user2, name='get_user2'),
    path('user2/other_boos/', v.other_boos2, name='other_boos2'),
]
