from django.urls import path
from django.conf.urls import include
from . import views as v

urlpatterns = [
    path('mvp1', v.play, name='play'),
    path('', v.discover, name='discover'),
    # path('profiler', v.profiler, name='profiler'),
    path('company/', v.company, name='company'),
    path('about/', v.about, name='about'),
    path('company/recruit/', v.company_recruit, name='company_recruit'),
    path('landing/', v.landing, name='landing'),
    path('zthinker/', v.zthinker, name='zthinker'),
    path('test/', v.test, name='test'),
    path('testbed/', v.testbed, name='testbed'),
    # path('memb/', v.memb, name='memb'),
    path('privacy/', v.privacy, name='privacy'),
    path('policy/', v.policy, name='policy'),
    path('recruit/', v.recruit, name='recruit'),
    path('app/ios/', v.app_ios, name='app_ios'),
    path('app/android/', v.app_android, name='app_android'),
    # path('accounts/', include('allauth.urls')),
    # path('login/', v.Login.as_view(), name='login'),
    path('logout/', v.Logout.as_view(), name='logout'),
    # path('authorpage/<int:boo_id>/', v.authorpage, name='authorpage'),
    # path('posts/', v.get_posts, name='get_posts'),
    # path('posts/ids/', v.get_iposts, name='get_iposts'),
    # path('posts/ids/', v.get_iposts, name='get_iposts'),
    # path('posts/iposts/', v.get_iposts, name='get_iposts'),
    path('posts/iposts/<str:type>/', v.get_iposts, name='get_iposts'),
    # path('posts/iposts/<int:boo_id>/', v.get_ibooposts, name='get_ibooposts'),
    path('post/<int:post_id>/', v.get_post, name='get_post'),
    path('post/<int:post_id>/boo/', v.get_boopost, name='get_boopost'),
    path('post/<int:post_id>/icomments/', v.get_icomments, name='get_icomments'),
    # path('post/<int:post_id>/comments/', v.get_comments, name='get_comments'),
    path('post/<int:post_id>/vote/', v.vote, name='vote'),
    path('post/<int:post_id>/voters/', v.voters, name='voters'),
    path('post/<int:post_id>/ivoters/<int:act>/', v.get_ivoters, name='get_ivoters'),
    path('post/save/', v.post_save, name='post_save'),
    path('post/<int:post_id>/delete/', v.post_delete, name='post_delete'),
    path('comment/<int:comment_id>/', v.get_comment, name='get_comment'),
    path('comment/<int:comment_id>/like/', v.like_comment, name='like_comment'),
    path('comment/<int:comment_id>/delike/', v.delike_comment, name='delike_comment'),
    path('comment/save/', v.comment_save, name='comment_save'),

    path('boos/iboos/<str:type>/', v.get_iboos, name='get_iboos'),
    path('boo/<int:boo_id>/follow/', v.follow, name='follow'),
    path('boo/<int:boo_id>/unfollow/', v.unfollow, name='unfollow'),
    path('boo/<int:boo_id>/set/', v.set_boo, name='set_boo'),
    path('boo/<int:boo_id>/network/', v.network, name='network'),
    # path('boo/<int:boo_id>/posts/', v.boo_posts, name='boo_posts'),
    # path('boo/<int:boo_id>/iposts/', v.get_ibooposts, name='get_ibooposts'),
    path('boo/<int:boo_id>/iposts/<str:type>/', v.get_ibooposts, name='get_ibooposts'),
    path('boo/<int:boo_id>/ifollowers/', v.get_ifollowers, name='get_ifollowers'),
    path('boo/<int:boo_id>/icollections/', v.get_icollections, name='get_icollections'),

    path('boo/<int:boo_id>/profile/pix/', v.boo_profilepix, name='boo_profilepix'),
    path('boo/<int:boo_id>/baseboo/', v.get_baseboo, name='get_baseboo'),
    # path('boo/<int:boo_id>/voter/', v.get_voter, name='get_voter'),
    # path('boo/<int:boo_id>/follower/', v.get_follower, name='get_follower'),
    # path('boo/<int:boo_id>/moreinfo/', v.boo_moreinfo, name='boo_moreinfo'),
    # path('boo/profile/save/', v.profile_save, name='profile_save'),
    path('boo/profile/delete/', v.profile_delete, name='profile_delete'),
    # path('boo/new/', v.boo_new, name='boo_new'),
    path('user/', v.get_user, name='get_user'),
    path('user/other_boos/', v.other_boos, name='other_boos'),

    # path('styletags/tag/<int:tag_id>', v.styletags_tag, name='styletags_tag'),
    # path('styletags/untag/<int:tag_id>', v.styletags_untag, name='styletags_untag'),
    #
    # path('fashiontems/tag/<int:item_id>', v.fashiontems_tag, name='fashiontems_tag'),
    # path('fashiontems/untag/<int:item_id>', v.fashiontems_untag, name='fashiontems_untag'),

    path('boo/save/', v.boo_save, name='boo_save'),
    # path('boo/create/', v.boo_create, name='boo_create'),

    path('search/<str:keywords>/', v.search, name='search'),
    path('search/pix/<int:pix_id>/', v.search_by_pix, name='search_by_pix'),
    path('search/keyword/<str:keyword>/', v.search_by_keyword, name='search_by_keyword'),
    path('search/collection/<int:collection_id>/', v.search_by_collection, name='search_by_collection'),

    path('link/add/', v.link_add, name='link_add'),
    path('link/edit/', v.link_edit, name='link_edit'),
    path('link/delete/<int:link_id>/', v.link_delete, name='link_delete'),

    path('mbti/<str:type>/iposts/', v.get_mbti_iposts, name='get_mbti_iposts'),
    # path('mbti/<str:type>/result/base/', v.mbtiresult_base, name='mbtiresult_base'),

    path('pix/ipixs/', v.get_ipixs, name='get_ipixs'),
    path('pix/ipixs/comb/<int:n>/', v.get_ipixs_comb, name='get_ipixs_comb'),
    path('pix/<int:pix_id>/', v.get_pix, name='get_pix'),

    path('collection/icols/', v.get_random_icols, name='get_random_icols'),
    # path('collection/icols/<int:owner_id>/', v.get_icols, name='get_icols'),
    path('collection/create/<str:name>/', v.create_collection, name='create_collection'),
    path('collection/<int:collection_id>/', v.get_collection, name='get_collection'),
    path('collection/<int:collection_id>/base/', v.get_collection_base, name='get_collection_base'),
    path('collection/<int:collection_id>/ipixs/', v.get_collection_ipixs, name='get_collection_ipixs'),
    path('collection/<int:collection_id>/ipicks/', v.get_ipicks, name='get_ipicks'),
    path('collection/<int:collection_id>/collect/<int:pix_id>/', v.collect_pix, name='collect_pix'),
    path('collection/<int:collection_id>/delpicks/<str:pick_ids>/', v.remove_picks, name='remove_picks'),

    path('pick/<int:pick_id>/', v.get_pick, name='get_pick'),

    path('signup/email/', v.email_signup, name='email_signup'),
    path('signup/email/check/', v.signup_email_check, name='signup_email_check'),
    path('signup/setbase/', v.signup_setbase, name='signup_setbase'),
    path('signup/setbase/change/', v.signup_setbase_change, name='signup_setbase_change'),
    # path('signup/setbase/mobile_verify_only/', v.signup_setbase_mobile_verify_only, name='signup_setbase_mobile_verify_only'),
    path('login/email/', v.email_login, name='email_login'),
    path('login/social/kakaotalk/', v.kakaotalk_login, name='kakaotalk_login'),

    # path('user/check/account/', v.acount_check, name='acount_check'),
    path('user2/', v.get_user2, name='get_user2'),
    path('user2/other_boos/', v.other_boos2, name='other_boos2'),

    path('stylevote/', v.stylevote, name='stylevote'),
    path('settle/', v.settle, name='settle'),
    path('transact/', v.transact, name='transact'),

    path('postage/<int:postage_id>/', v.get_postage, name='get_postage'),

    path('contentwork/<int:id>/', v.get_contentwork, name='get_contentwork'),
    path('contentwork/<int:id>/ipostages/', v.get_contentwork_ipostages, name='get_contentwork_ipostages'),
    path('contentwork/<int:id>/resultize/', v.contentwork_resultize, name='contentwork_resultize'),

    path('postage/<int:postage_id>/contentvote/', v.contentvote, name='contentvote'),
    path('notice/preset/', v.notice_preset, name='notice_preset'),

    path('research/iresearches/', v.get_iresearches, name='get_iresearches'),
    # path('research/iresearches/onwork', v.get_iresearches_onwork, name='get_iresearches_onwork'),
    path('research/<int:research_id>/', v.get_research, name='get_research'),
    path('research/<int:research_id>/done/', v.research_done, name='research_done'),
    path('research/<int:research_id>/iresearchitems/', v.get_iresearchitems, name='get_iresearchitems'),
    path('research/item/<int:researchitem_id>/', v.get_researchitem, name='get_researchitem'),
    path('research/<int:research_id>/item/<int:researchitem_id>/answer/<answer>/', v.researchitem_answer, name='researchitem_answer'),
    path('research/checkingame/', v.get_checkingame, name='get_checkingame'),

    # path('brand/isupportbrands/', v.get_isupportbrands, name='get_isupportbrands'),
    path('brand/<int:brand_id>/', v.get_brand, name='get_brand'),
    # path('brand/<int:brand_id>/isupports/', v.get_isupports, name='get_isupports'),
    path('support/<int:support_id>/', v.get_support, name='get_support'),
    path('support/isupports/', v.get_isupports, name='get_isupports'),
    path('support/isupports/my/', v.get_isupports_my, name='get_isupports_my'),

    path('coffeecoupon/<int:coffeecoupon_id>/', v.get_coffeecoupon, name='get_coffeecoupon'),
    path('coffeecoupon/icoffeecoupons/', v.get_icoffeecoupons, name='get_icoffeecoupons'),

    # path('shoptem/<int:shoptem_id>/buy/', v.buy_shoptem, name='buy_shoptem'),
    path('shoptem/<int:shoptem_id>/', v.get_shoptem, name='get_shoptem'),
    path('shoptem/ishoptems/', v.get_ishoptems, name='get_ishoptems'),

    path('raffle/<int:raffle_id>/', v.get_raffle, name='get_raffle'),
    path('raffle/<int:raffle_id>/send_request/', v.raffle_send_request, name='raffle_send_request'),
    path('raffle/iraffles/', v.get_iraffles, name='get_iraffles'),
    path('raffle/iraffles/my/', v.get_iraffles_my, name='get_iraffles_my'),

    path('item/<int:item_id>/', v.get_item, name='get_item'),

    path('label/style/<int:label_id>/', v.get_stylelabel, name='get_stylelabel'),
    path('label/item/<int:label_id>/', v.get_itemlabel, name='get_itemlabel'),
    path('label/istylelabels/', v.get_istylelabels, name='get_istylelabels'),
    path('label/iitemlabels/', v.get_iitemlabels, name='get_iitemlabels'),
    path('label/edit/', v.edit_mylabels, name='edit_mylabels'),
    path('label/save/', v.save_mylabels, name='save_mylabels'),

    path('flashgame/<int:flashgame_id>/', v.get_flashgame, name='get_flashgame'),
    path('flashgame/iflashgames/', v.get_iflashgames, name='get_iflashgames'),
    path('flashgame/answer/', v.flashgame_answer, name='flashgame_answer'),

    path('balancegame/stat/', v.balancegame_stat, name='balancegame_stat'),
    path('balancegame/stat/2/', v.balancegame_stat2, name='balancegame_stat2'),
    path('balancegame/vote/', v.balancegame_vote, name='balancegame_vote'),

    path('pixpair/ipixs/', v.get_pixpair_ipixs, name='get_pixpair_ipixs'),

    path('tag/<int:tag_id>/', v.get_tag, name='get_tag'),
    path('tag/itags/', v.get_itags, name='get_itags'),
    path('tag/itags/<int:n>/', v.get_itags_many, name='get_itags_many'),

    path('mobile/send_authkey/', v.send_mobile_authkey, name='send_mobile_authkey'),
    path('mobile/verify/', v.mobile_verify, name='mobile_verify'),
    path('mobile/verify/save/', v.mobile_verify_save, name='mobile_verify_save'),

    # path('notify/shopping/<int:trans_id>/', v.notify_shopping, name='notify_shopping'),
]
